### ISSUE TITLE
주문 기능 개발

### ISSUE THREAD

**Issue by mistyblue0302** [mistyblue0302/food_ordering_service#33]
## 📄 Summary
> 주문 기능을 개발합니다.

## ✅ Tasks

- [x] 주문 엔티티 생성
- [x] 클라이언트의 JWT 토큰을 포함한 주문 요청
- [x] 토큰 유효성 검증
- [x] 주문 처리 로직 작성

## 🙋🏻 More
>
