### ISSUE TITLE
사장님 도메인 기능 개발

### ISSUE THREAD

**Issue by mistyblue0302** [mistyblue0302/food_ordering_service#45]
## 📄 Summary
> 사장님 역할 추가 및 회원가입 로직을 수정합니다.

## ✅ Tasks

- [x] 사장님 Role 추가
- [x] 기존 회원가입 로직에 역할 정보를 포함하는 클레임 추가
- [x] 테스트 코드 작성

## 🙋🏻 More
>
