### ISSUE TITLE
배달 요청 API 개발

### ISSUE THREAD

**Issue by mistyblue0302** [mistyblue0302/food_ordering_service#46]
## 📄 Summary
> 사장님이 배달을 요청하는 API를 개발합니다.

## ✅ Tasks

- [x] 배달 요청 API 구현
- [x] 배달 기능을 위한 enum 생성
- [x] 테스트 코드 작성

## 🙋🏻 More
>
